dcConsData = [
	{ name: "화랑몰루.jpg", keywords: ["화랑몰루"], tags: ["몰?루"] },
	{ name: "개구리갑분싸.gif", keywords: ["페페실망"], tags: ["페페"] },
	{ name: "개구리빵야1.png", keywords: ["페페권총"], tags: ["페페"] },
	{ name: "개구리빵야2.png", keywords: ["페페권총2"], tags: ["페페"] },
	{ name: "개구리화남.png", keywords: ["페페분노"], tags: ["페페"] },
	{ name: "더블앵무.gif", keywords: ["더블앵무"], tags: ["앵무"] },
	{ name: "흠.png", keywords: ["흠"], tags: ["흠"] },
	{ name: "흠발퀄.png", keywords: ["발퀄흠"], tags: ["흠"] },
	{ name: "흠회전1.gif", keywords: ["회전흠1"], tags: ["흠"] },
	{ name: "흠회전2.gif", keywords: ["회전흠2"], tags: ["흠"] },
	{ name: "흠회전3.gif", keywords: ["회전흠3"], tags: ["흠"] },
	{ name: "흠왜곡.gif", keywords: ["왜곡흠"], tags: ["흠"] },
	{ name: "제리감사.gif", keywords: ["제리감사"], tags: ["제리"] },
	{ name: "1등급.jpg", keywords: ["1등급"], tags: ["아잇"] },
	{ name: "로치.jpg", keywords: ["외않됨?"], tags: ["유희왕"] },
	{ name: "무효아님.jpg", keywords: ["싸이크론"], tags: ["유희왕"] },
	{ name: "자일리통.jpg", keywords: ["300원"], tags: ["철권"] },
	{ name: "콩콩2.jpg", keywords: ["콩콩이"], tags: ["롤"] },
	{ name: "꿀벌1.jpg", keywords: ["꿀벌1"], tags: ["야꿀벌"] },
	{ name: "꿀벌2.jpg", keywords: ["꿀벌2"], tags: ["야꿀벌"] },
	{ name: "꿀벌3.jpg", keywords: ["꿀벌3"], tags: ["야꿀벌"] },
	{ name: "좋은말축하해.gif", keywords: ["축하해"], tags: ["좋은말"] },
];

