document.addEventListener('DOMContentLoaded', () => {
  const imageGrid = document.getElementById('imageGrid');

  for (let i = 0; i <= dcConsData.length; i++) {
    const img = document.createElement('img');
    img.src = `images/${dcConsData[i].name}`;
    img.alt = `${dcConsData[i].keywords}`;
    img.addEventListener('click', () => {
      displayText.textContent = '~' + img.alt;
      // Copy alt text to clipboard
      const tempInput = document.createElement('input');
      document.body.appendChild(tempInput);
      tempInput.value = '~' + img.alt;
      tempInput.select();
      document.execCommand('copy');
      document.body.removeChild(tempInput);
      copied.textContent = '복사되었습니다. 채팅창에 붙여넣기 하세요!';
      setInterval(() => {
        displayText.textContent = '이미지를 클릭하면 복사가 됩니다.';
        copied.textContent = '\u00A0';
      }, 1500);
    });
    imageGrid.appendChild(img);
  }
});

const dcConsData = [
  { name: '페페갑분싸.gif', keywords: ['페페실망'], tags: ['페페'] },
  { name: '페페빵야1.png', keywords: ['페페빵야1'], tags: ['페페'] },
  { name: '페페빵야2.png', keywords: ['페페빵야2'], tags: ['페페'] },
  { name: '페페광대.png', keywords: ['페페광대'], tags: ['페페'] },
  { name: '페페화남.png', keywords: ['페페분노'], tags: ['페페'] },
  { name: '페페교수.png', keywords: ['페페자살'], tags: ['페페'] },
  { name: '페페예스.png', keywords: ['페페예스'], tags: ['페페'] },
  { name: '페페노.png', keywords: ['페페노'], tags: ['페페'] },
  { name: '페페vr.png', keywords: ['페페vr'], tags: ['페페'] },
  { name: '페페덜덜.gif', keywords: ['페페덜덜'], tags: ['페페'] },
  { name: '페페덜덜덜.gif', keywords: ['페페덜덜덜'], tags: ['페페'] },
  { name: '페페아찔.gif', keywords: ['페페아찔'], tags: ['페페'] },
  { name: '페페성탄절.gif', keywords: ['페페성탄절'], tags: ['페페'] },
  { name: '페페주먹.gif', keywords: ['페페주먹'], tags: ['페페'] },
  { name: '페페빼액.png', keywords: ['페페빼액'], tags: ['페페'] },
  { name: '페페무슨일.jpg', keywords: ['페페무슨일'], tags: ['페페'] },
  { name: '앵그리페페.png', keywords: ['페페앵그리'], tags: ['페페'] },
  { name: '페바.gif', keywords: ['페페바이'], tags: ['페페'] },
  { name: '페페비트.gif', keywords: ['페페비트'], tags: ['페페'] },
  { name: '페페물음표.png', keywords: ['페페물음표'], tags: ['페페'] },
  { name: '페페따봉.png', keywords: ['페페따봉'], tags: ['페페'] },
  { name: '페페클럽.gif', keywords: ['페페클럽'], tags: ['페페'] },
  { name: '페페팝콘.gif', keywords: ['페페팝콘'], tags: ['페페'] },
  { name: '페페그런건.gif', keywords: ['페페그런건'], tags: ['페페'] },
  { name: '혼란앵무.gif', keywords: ['혼란앵무'], tags: ['앵무'] },
  { name: '더블앵무.gif', keywords: ['더블앵무'], tags: ['앵무'] },
  { name: '스핀앵무.gif', keywords: ['스핀앵무'], tags: ['앵무'] },
  { name: '문워크앵무.gif', keywords: ['문워크앵무'], tags: ['앵무'] },
  { name: '팝콘앵무.gif', keywords: ['팝콘앵무'], tags: ['앵무'] },
  { name: '눈물앵무.gif', keywords: ['눈물앵무'], tags: ['앵무'] },
  { name: '기가차드1.webp', keywords: ['기가차드1'], tags: ['기가채드'] },
  { name: '제드하하.png', keywords: ['제드하하'], tags: ['롤'] },
  { name: '티모따봉.png', keywords: ['티모따봉'], tags: ['롤'] },
  { name: '직스따봉.png', keywords: ['직스따봉'], tags: ['롤'] },
  { name: '꿀벌1.png', keywords: ['꿀벌1'], tags: ['롤'] },
  { name: '꿀벌2.png', keywords: ['꿀벌2'], tags: ['롤'] },
  { name: '꿀벌3.png', keywords: ['꿀벌3'], tags: ['롤'] },
  { name: '플.png', keywords: ['점멸'], tags: ['롤'] },
  { name: '강타.png', keywords: ['강타'], tags: ['롤'] },
  { name: '점화.png', keywords: ['점화'], tags: ['롤'] },
  { name: '회복.png', keywords: ['회복'], tags: ['롤'] },
  { name: '보호막.png', keywords: ['보호막'], tags: ['롤'] },
  { name: '유체화.png', keywords: ['유체화'], tags: ['롤'] },
  { name: '텔.png', keywords: ['텔'], tags: ['롤'] },
  { name: '존야.png', keywords: ['존야'], tags: ['롤'] },
  { name: '흠.png', keywords: ['흠'], tags: ['흠'] },
  { name: '흠스웩.png', keywords: ['스웩흠'], tags: ['흠'] },
  { name: '흠흠흠.png', keywords: ['흠흠흠'], tags: ['흠'] },
  { name: '흠란.gif', keywords: ['혼란흠'], tags: ['흠'] },
  { name: '흠회전1.gif', keywords: ['회전흠1'], tags: ['흠'] },
  { name: '흠회전2.gif', keywords: ['회전흠2'], tags: ['흠'] },
  { name: '흠회전3.gif', keywords: ['회전흠3'], tags: ['흠'] },
  { name: '흠발퀄.png', keywords: ['발퀄흠'], tags: ['흠'] },
  { name: '흠고퀄.png', keywords: ['고퀄흠'], tags: ['흠'] },
  { name: '흠왜곡.gif', keywords: ['왜곡흠'], tags: ['흠'] },
  { name: '제리감사.gif', keywords: ['제리감사'], tags: ['톰과 제리'] },
  { name: '제리딸딸1.gif', keywords: ['제리딸딸1'], tags: ['톰과 제리'] },
  { name: '제리딸딸2.gif', keywords: ['제리딸딸2'], tags: ['톰과 제리'] },
  { name: '제리안녕.gif', keywords: ['제리안녕'], tags: ['톰과 제리'] },
  { name: '제리헐크.gif', keywords: ['제리헐크'], tags: ['톰과 제리'] },
  { name: '제리경악.gif', keywords: ['제리경악'], tags: ['톰과 제리'] },
  { name: '제리멍멍.gif', keywords: ['제리멍멍'], tags: ['톰과 제리'] },
  { name: '제리애원.gif', keywords: ['제리애원'], tags: ['톰과 제리'] },
  { name: '제리하트.gif', keywords: ['제리하트'], tags: ['톰과 제리'] },
  { name: '제리폭소.gif', keywords: ['제리폭소'], tags: ['톰과 제리'] },
  { name: '제리못마땅.gif', keywords: ['제리못마땅'], tags: ['톰과 제리'] },
  { name: '제리역돌격.gif', keywords: ['제리역돌격'], tags: ['톰과 제리'] },
  { name: '톰폭소.gif', keywords: ['톰폭소'], tags: ['톰과 제리'] },
  { name: '톰찬성.gif', keywords: ['톰찬성'], tags: ['톰과 제리'] },
  { name: '톰분노.gif', keywords: ['톰분노'], tags: ['톰과 제리'] },
  { name: '톰광기.gif', keywords: ['톰광기'], tags: ['톰과 제리'] },
  { name: '톰애원.gif', keywords: ['톰애원'], tags: ['톰과 제리'] },
  { name: '톰감사.gif', keywords: ['톰감사'], tags: ['톰과 제리'] },
  { name: '톰안도.gif', keywords: ['톰안도'], tags: ['톰과 제리'] },
  { name: '톰포옹.gif', keywords: ['톰포옹'], tags: ['톰과 제리'] },
  { name: '톰덜덜.gif', keywords: ['톰덜덜'], tags: ['톰과 제리'] },
  { name: '톰경례.gif', keywords: ['톰경례'], tags: ['톰과 제리'] },
  { name: '톰박수.gif', keywords: ['톰박수'], tags: ['톰과 제리'] },
  { name: '톰반대.gif', keywords: ['톰반대'], tags: ['톰과 제리'] },
  { name: '갈1.png', keywords: ['갈1'], tags: ['침팬치콘'] },
  { name: '갈2.png', keywords: ['갈2'], tags: ['침팬치콘'] },
  { name: '소신발언.png', keywords: ['소신발언'], tags: ['침팬치콘'] },
  { name: '신앙이란.png', keywords: ['신앙이란'], tags: ['침팬치콘'] },
  { name: '이대로만.png', keywords: ['이대로만'], tags: ['침팬치콘'] },
  { name: '이제뭐함.png', keywords: ['이제뭐함'], tags: ['침팬치콘'] },
  { name: '크으으으.png', keywords: ['크으으으'], tags: ['침팬치콘'] },
  { name: '헐레벌떡.png', keywords: ['헐레벌떡'], tags: ['침팬치콘'] },
  { name: '함봐줍시다.gif', keywords: ['함봐줍시다'], tags: ['침팬치콘'] },
  { name: '고퀄소신발언.gif', keywords: ['소신발언2'], tags: ['침팬치콘'] },
  { name: '고퀄갈.gif', keywords: ['갈'], tags: ['침팬치콘'] },
  { name: '고퀄크으으.gif', keywords: ['크으으으2'], tags: ['침팬치콘'] },
  { name: '고퀄이제뭐함.gif', keywords: ['이제뭐함2'], tags: ['침팬치콘'] },
  { name: '이상해요.png', keywords: ['이상해요'], tags: ['동물콘'] },
  { name: '안아줘요.png', keywords: ['안아줘요'], tags: ['동물콘'] },
  { name: '좋아해요.png', keywords: ['좋아해요'], tags: ['동물콘'] },
  { name: '싫은데요.png', keywords: ['싫은데요'], tags: ['동물콘'] },
  { name: '푸하하.png', keywords: ['푸하하'], tags: ['동물콘'] },
  { name: '엘레레.png', keywords: ['엘레레'], tags: ['동물콘'] },
  { name: '먹을만하네요.png', keywords: ['먹을만하네요'], tags: ['동물콘'] },
  { name: '화났어요.png', keywords: ['화났어요'], tags: ['동물콘'] },
  { name: '사딸라.png', keywords: ['사딸라'], tags: ['야인시대'] },
  { name: '오케이땡큐.png', keywords: ['오케이땡큐'], tags: ['야인시대'] },
  { name: '심영박수.gif', keywords: ['심영박수'], tags: ['야인시대'] },
  { name: '심영박수2.gif', keywords: ['심영박수2'], tags: ['야인시대'] },
  { name: '심영띠용.gif', keywords: ['심영띠용'], tags: ['야인시대'] },
  { name: '심영런.gif', keywords: ['심영런'], tags: ['야인시대'] },
  { name: '의사양반.gif', keywords: ['의사양반'], tags: ['야인시대'] },
  { name: '안하겠소.gif', keywords: ['안하겠소'], tags: ['야인시대'] },
  { name: '상하이조.gif', keywords: ['상하이조'], tags: ['야인시대'] },
  { name: '연막.gif', keywords: ['연막'], tags: ['야인시대'] },
  { name: '앙겟썸.gif', keywords: ['앙겟썸'], tags: ['야인시대'] },
  { name: '폭발.gif', keywords: ['폭발'], tags: ['야인시대'] },
  { name: '좋은말좋겠다.gif', keywords: ['좋겠다'], tags: ['좋은말'] },
  { name: '좋은말네말맞.gif', keywords: ['네말이맞아'], tags: ['좋은말'] },
  { name: '좋은말짱이야.gif', keywords: ['짱이야'], tags: ['좋은말'] },
  { name: '좋은말멋있다.gif', keywords: ['정말멋있다'], tags: ['좋은말'] },
  { name: '좋은말축하해.gif', keywords: ['축하해'], tags: ['좋은말'] },
  { name: '좋은말괜찮아.gif', keywords: ['괜찮아'], tags: ['좋은말'] },
  { name: '좋은말구라야.gif', keywords: ['구라야'], tags: ['좋은말'] },
  { name: '좋은말맛있겠다.gif', keywords: ['맛있겠다'], tags: ['좋은말'] },
  { name: '좋은말멋진인생.gif', keywords: ['멋진인생'], tags: ['좋은말'] },
  { name: '좋은말재밌다.gif', keywords: ['재밌다'], tags: ['좋은말'] },
  { name: '좋은말안됐네.gif', keywords: ['안됐네'], tags: ['좋은말'] },
  { name: '온두루어.gif', keywords: ['온두루어'], tags: ['라이더'] },
  { name: '닷디아나.gif', keywords: ['닷디아나'], tags: ['라이더'] },
  { name: '보노보노.gif', keywords: ['보노보노'], tags: ['라이더'] },
  { name: '게게게.gif', keywords: ['게게게'], tags: ['라이더'] },
  { name: '마이데쇼.gif', keywords: ['마이데쇼'], tags: ['라이더'] },
  { name: '황금계단.gif', keywords: ['황금계단'], tags: ['라이더'] },
  { name: '1등급.jpg', keywords: ['1등급'], tags: ['기타'] },
  { name: '따꺼.gif', keywords: ['따꺼'], tags: ['기타'] },
  { name: 'rgb차이.gif', keywords: ['rgb차이'], tags: ['기타'] },
  { name: 'rgb.gif', keywords: ['rgb'], tags: ['기타'] },
  { name: '리듬스탈.gif', keywords: ['리듬스탈'], tags: ['기타'] },
  { name: '타이핑.gif', keywords: ['타이핑'], tags: ['기타'] },
  { name: '프로그래밍.gif', keywords: ['프로그래밍'], tags: ['기타'] },
  { name: '지식의보고.png', keywords: ['지식의보고1'], tags: ['기타'] },
  { name: '지식의보고2.png', keywords: ['지식의보고2'], tags: ['기타'] },
  { name: '시공조아.png', keywords: ['시공조아'], tags: ['기타'] },
  { name: '럼프박수.gif', keywords: ['럼프박수'], tags: ['기타'] },
  { name: '나만아니면1.gif', keywords: ['호동콘1'], tags: ['기타'] },
  { name: '나만아니면2.gif', keywords: ['호동콘2'], tags: ['기타'] },
  { name: '나만아니면3.gif', keywords: ['호동콘3'], tags: ['기타'] },
  { name: '야스각1.png', keywords: ['야스각1'], tags: ['기타'] },
  { name: '야스각2.png', keywords: ['야스각2'], tags: ['기타'] },
  { name: '야스야스.png', keywords: ['야스야스'], tags: ['기타'] },
  { name: '꼴받는몰루1.gif', keywords: ['몰루1'], tags: ['기타'] },
  { name: '꼴받는몰루2.gif', keywords: ['몰루2'], tags: ['기타'] },
  { name: '꼴받는몰루3.gif', keywords: ['몰루3'], tags: ['기타'] },
  { name: '봇치경련.gif', keywords: ['봇치경련'], tags: ['기타'] },
  { name: '봇치도리.gif', keywords: ['봇치도리'], tags: ['기타'] },
  { name: '봇치박수.gif', keywords: ['봇치박수'], tags: ['기타'] },
  { name: '봇치발작.gif', keywords: ['봇치발작'], tags: ['기타'] },
  { name: '볼트공중.png', keywords: ['볼트공중'], tags: ['볼트보이콘'] },
  { name: '볼트넷여친.png', keywords: ['볼트넷여친'], tags: ['볼트보이콘'] },
  { name: '볼트넷친구.png', keywords: ['볼트넷친구'], tags: ['볼트보이콘'] },
  { name: '볼트동정.png', keywords: ['볼트동정'], tags: ['볼트보이콘'] },
  { name: '볼트가정사.png', keywords: ['볼트가정사'], tags: ['볼트보이콘'] },
  { name: '볼트등골.png', keywords: ['볼트등골'], tags: ['볼트보이콘'] },
  { name: '볼트병신.png', keywords: ['볼트병신'], tags: ['볼트보이콘'] },
  { name: '볼트나무.png', keywords: ['볼트나무'], tags: ['볼트보이콘'] },
  { name: '볼트대머리.png', keywords: ['볼트대머리'], tags: ['볼트보이콘'] },
  { name: '볼트침대.png', keywords: ['볼트침대'], tags: ['볼트보이콘'] },
  { name: '볼트활활.png', keywords: ['볼트활활'], tags: ['볼트보이콘'] },
  { name: '볼트댕댕.png', keywords: ['볼트댕댕'], tags: ['볼트보이콘'] },
  { name: '볼트기계.png', keywords: ['볼트기계'], tags: ['볼트보이콘'] },
  { name: '볼트결혼.png', keywords: ['볼트결혼'], tags: ['볼트보이콘'] },
  {
    name: '볼트비밀친구.png',
    keywords: ['볼트비밀친구'],
    tags: ['볼트보이콘'],
  },
  { name: '볼트군인.png', keywords: ['볼트군인'], tags: ['볼트보이콘'] },
  {
    name: '볼트닌자.png',
    keywords: ['볼트닌자', '볼트대게'],
    tags: ['볼트보이콘'],
  },
  { name: '볼트인육.png', keywords: ['볼트인육'], tags: ['볼트보이콘'] },
  { name: '볼트핫산.png', keywords: ['볼트핫산'], tags: ['볼트보이콘'] },
  { name: '볼트주사.png', keywords: ['볼트주사'], tags: ['볼트보이콘'] },
  { name: '볼트빼액.png', keywords: ['볼트빼액'], tags: ['볼트보이콘'] },
  { name: '볼트꺼져.png', keywords: ['볼트꺼져'], tags: ['볼트보이콘'] },
  { name: '볼트닥쳐.png', keywords: ['볼트닥쳐'], tags: ['볼트보이콘'] },
  { name: '볼트안마.png', keywords: ['볼트안마'], tags: ['볼트보이콘'] },
  { name: '볼트망치.png', keywords: ['볼트망치'], tags: ['볼트보이콘'] },
  { name: '볼트빠따.png', keywords: ['볼트빠따'], tags: ['볼트보이콘'] },
  { name: '볼트수류탄.png', keywords: ['볼트수류탄'], tags: ['볼트보이콘'] },
  { name: '볼트전기톱.png', keywords: ['볼트전기톱'], tags: ['볼트보이콘'] },
  { name: '볼트장전.png', keywords: ['볼트장전'], tags: ['볼트보이콘'] },
  { name: '볼트저격.png', keywords: ['볼트저격'], tags: ['볼트보이콘'] },
  { name: '볼트라이플.png', keywords: ['볼트라이플'], tags: ['볼트보이콘'] },
  { name: '볼트화염병.png', keywords: ['볼트화염병'], tags: ['볼트보이콘'] },
  { name: '볼트주먹.png', keywords: ['볼트주먹'], tags: ['볼트보이콘'] },
  { name: '볼트컴온.png', keywords: ['볼트컴온'], tags: ['볼트보이콘'] },
  { name: '볼트투창.png', keywords: ['볼트투창'], tags: ['볼트보이콘'] },
  { name: '볼트아킴보.png', keywords: ['볼트아킴보'], tags: ['볼트보이콘'] },
  { name: '볼트고인.png', keywords: ['볼트고인'], tags: ['볼트보이콘'] },
  { name: '볼트부활.png', keywords: ['볼트부활'], tags: ['볼트보이콘'] },
  { name: '볼트띠용.png', keywords: ['볼트띠용'], tags: ['볼트보이콘'] },
  { name: '볼트신문.png', keywords: ['볼트신문'], tags: ['볼트보이콘'] },
  { name: '볼트눈물.png', keywords: ['볼트눈물'], tags: ['볼트보이콘'] },
  { name: '볼트투시.png', keywords: ['볼트투시'], tags: ['볼트보이콘'] },
  { name: '볼트토끼.png', keywords: ['볼트토끼'], tags: ['볼트보이콘'] },
  { name: '볼트포기.png', keywords: ['볼트포기'], tags: ['볼트보이콘'] },
  { name: '볼트자살.png', keywords: ['볼트자살'], tags: ['볼트보이콘'] },
  { name: '볼트에쎔.png', keywords: ['볼트에쎔'], tags: ['볼트보이콘'] },
  { name: '볼트딸딸.png', keywords: ['볼트딸딸'], tags: ['볼트보이콘'] },
  { name: '볼트음주.png', keywords: ['볼트음주'], tags: ['볼트보이콘'] },
  { name: '볼트수면.png', keywords: ['볼트수면'], tags: ['볼트보이콘'] },
  { name: '볼트우승.png', keywords: ['볼트우승'], tags: ['볼트보이콘'] },
  { name: '볼트루저.png', keywords: ['볼트루저'], tags: ['볼트보이콘'] },
  { name: '볼트구토.png', keywords: ['볼트구토'], tags: ['볼트보이콘'] },
  { name: '볼트예수.png', keywords: ['볼트예수'], tags: ['볼트보이콘'] },
  { name: '볼트심리.png', keywords: ['볼트심리'], tags: ['볼트보이콘'] },
  { name: '볼트연설.png', keywords: ['볼트연설'], tags: ['볼트보이콘'] },
  { name: '볼트엄격.png', keywords: ['볼트엄격'], tags: ['볼트보이콘'] },
  { name: '볼트진지.png', keywords: ['볼트진지'], tags: ['볼트보이콘'] },
  { name: '볼트근엄.png', keywords: ['볼트근엄'], tags: ['볼트보이콘'] },
  { name: '볼트펄럭.png', keywords: ['볼트펄럭'], tags: ['볼트보이콘'] },
  { name: '볼트답답.png', keywords: ['볼트답답'], tags: ['볼트보이콘'] },
  { name: '볼트절망.png', keywords: ['볼트절망'], tags: ['볼트보이콘'] },
  { name: '볼트관전.png', keywords: ['볼트관전'], tags: ['볼트보이콘'] },
  { name: '볼트통수.png', keywords: ['볼트통수'], tags: ['볼트보이콘'] },
  { name: '볼트연주.png', keywords: ['볼트연주'], tags: ['볼트보이콘'] },
  { name: '볼트파오후.png', keywords: ['볼트파오후'], tags: ['볼트보이콘'] },
  { name: '볼트딴딴.png', keywords: ['볼트딴딴'], tags: ['볼트보이콘'] },
  { name: '볼트처형.png', keywords: ['볼트처형'], tags: ['볼트보이콘'] },
  { name: '볼트명상.png', keywords: ['볼트명상'], tags: ['볼트보이콘'] },
  { name: '볼트마약.png', keywords: ['볼트마약'], tags: ['볼트보이콘'] },
  { name: '볼트떠남.png', keywords: ['볼트떠남'], tags: ['볼트보이콘'] },
  { name: '볼트근육.png', keywords: ['볼트근육'], tags: ['볼트보이콘'] },
  { name: '볼트자본.png', keywords: ['볼트자본'], tags: ['볼트보이콘'] },
];
